"use client"

import { AuthGate } from "@/components/auth-gate"
import { Header } from "@/components/layout/header"
import { HeadingLg, BodyMd } from "@/components/ui/typography"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { AlertTriangle, CheckCircle, ShieldAlert } from "lucide-react"

export default function FraudAlertsPage() {
  const alerts = [
    { id: "ALT-901", type: "GPS_SPOOFING", entity: "Driver #842", severity: "CRITICAL", time: "2m ago", status: "OPEN" },
    { id: "ALT-902", type: "DUPLICATE_ACCOUNTS", entity: "User +93700123456", severity: "HIGH", time: "15m ago", status: "OPEN" },
    { id: "ALT-903", type: "REFERRAL_FRAUD", entity: "Device ID X9F22", severity: "MEDIUM", time: "1h ago", status: "RESOLVED" },
  ]

  return (
    <AuthGate roles={["ADMIN"]}>
      <div className="flex flex-col min-h-screen bg-background/50">
        <Header />
        <main className="flex-1 container py-8">
          <div className="flex justify-between items-end mb-8">
            <div>
              <HeadingLg className="mb-2 flex items-center gap-2">
                <AlertTriangle className="h-8 w-8 text-red-500" />
                Real-Time Fraud Alerts
              </HeadingLg>
              <BodyMd className="text-muted-foreground">
                Automated flags generated by the Risk Scoring Engine.
              </BodyMd>
            </div>
          </div>

          <Card className="glass-premium border-red-500/20">
            <CardContent className="p-0">
              <table className="w-full text-sm text-left">
                <thead className="bg-muted/50 border-b">
                  <tr>
                    <th className="px-6 py-4">Alert ID</th>
                    <th className="px-6 py-4">Type</th>
                    <th className="px-6 py-4">Target Entity</th>
                    <th className="px-6 py-4">Severity</th>
                    <th className="px-6 py-4">Time</th>
                    <th className="px-6 py-4 text-right">Actions</th>
                  </tr>
                </thead>
                <tbody>
                  {alerts.map(a => (
                    <tr key={a.id} className="border-b hover:bg-muted/20">
                      <td className="px-6 py-4 font-mono text-xs">{a.id}</td>
                      <td className="px-6 py-4 font-bold">{a.type}</td>
                      <td className="px-6 py-4">{a.entity}</td>
                      <td className="px-6 py-4">
                        <Badge variant={a.severity === 'CRITICAL' ? 'destructive' : a.severity === 'HIGH' ? 'default' : 'secondary'} className="text-[10px]">
                          {a.severity}
                        </Badge>
                      </td>
                      <td className="px-6 py-4 text-muted-foreground">{a.time}</td>
                      <td className="px-6 py-4 text-right">
                        {a.status === 'OPEN' ? (
                          <div className="flex justify-end gap-2">
                            <Button size="sm" variant="outline" className="h-8 border-primary/50 text-primary hover:bg-primary/10">
                              <ShieldAlert className="h-4 w-4 mr-1" /> Open Case
                            </Button>
                            <Button size="sm" variant="ghost" className="h-8 text-muted-foreground hover:text-primary">
                              <CheckCircle className="h-4 w-4 mr-1" /> Resolve
                            </Button>
                          </div>
                        ) : (
                          <Badge variant="outline" className="text-muted-foreground">RESOLVED</Badge>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </CardContent>
          </Card>
        </main>
      </div>
    </AuthGate>
  )
}
