"use client"

import { AuthGate } from "@/components/auth-gate"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { AlertTriangle, CheckCircle, ShieldAlert } from "lucide-react"
import { AdminPageHeader } from "@/components/admin/admin-page-header"

export default function FraudAlertsPage() {
  const alerts = [
    { id: "ALT-901", type: "GPS_SPOOFING", entity: "Driver #842", severity: "CRITICAL", time: "2m ago", status: "OPEN" },
    { id: "ALT-902", type: "DUPLICATE_ACCOUNTS", entity: "User +93700123456", severity: "HIGH", time: "15m ago", status: "OPEN" },
    { id: "ALT-903", type: "REFERRAL_FRAUD", entity: "Device ID X9F22", severity: "MEDIUM", time: "1h ago", status: "RESOLVED" },
  ]

  return (
    <AuthGate roles={["ADMIN"]}>
      <main className="min-h-screen px-4 py-8 md:px-8">
        <div className="mx-auto max-w-7xl space-y-6">
          <AdminPageHeader
            title="Real-Time Fraud Alerts"
            subtitle="Automated flags generated by the Risk Scoring Engine."
          />

          <Card className="glass-premium border-destructive/20 shadow-2xl overflow-hidden">
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full text-sm text-left">
                  <thead className="border-b border-primary/10 bg-background/50 text-[10px] uppercase font-black tracking-widest text-muted-foreground">
                    <tr>
                      <th className="px-6 py-4">Alert ID</th>
                      <th className="px-6 py-4">Type</th>
                      <th className="px-6 py-4">Target Entity</th>
                      <th className="px-6 py-4">Severity</th>
                      <th className="px-6 py-4">Time</th>
                      <th className="px-6 py-4 text-right">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {alerts.map(a => (
                      <tr key={a.id} className="border-b border-primary/5 hover:bg-primary/5 transition-colors">
                        <td className="px-6 py-4 font-mono text-[10px] text-muted-foreground">{a.id}</td>
                        <td className="px-6 py-4 font-black uppercase tracking-tight text-xs">{a.type}</td>
                        <td className="px-6 py-4 font-medium">{a.entity}</td>
                        <td className="px-6 py-4">
                          <Badge variant={a.severity === 'CRITICAL' ? 'destructive' : a.severity === 'HIGH' ? 'default' : 'secondary'} className="text-[10px] font-black uppercase">
                            {a.severity}
                          </Badge>
                        </td>
                        <td className="px-6 py-4 text-[10px] font-bold text-muted-foreground uppercase">{a.time}</td>
                        <td className="px-6 py-4 text-right">
                          {a.status === 'OPEN' ? (
                            <div className="flex justify-end gap-2">
                              <Button size="sm" variant="outline" className="font-bold border-primary/20 text-primary hover:bg-primary/10">
                                <ShieldAlert className="h-4 w-4 mr-1" /> Open Case
                              </Button>
                              <Button size="sm" variant="ghost" className="font-bold text-muted-foreground hover:text-primary">
                                <CheckCircle className="h-4 w-4 mr-1" /> Resolve
                              </Button>
                            </div>
                          ) : (
                            <Badge variant="outline" className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">RESOLVED</Badge>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>
        </div>
      </main>
    </AuthGate>
  )
}
