substitutions:
  _REGION: asia-south1
  _REPOSITORY: noori
  _SERVICE: noori-web
  _BACKEND_URL: https://noori-backend-750921372930.asia-south1.run.app

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_URL=${_BACKEND_URL}/api
      - --build-arg
      - NEXT_PUBLIC_SOCKET_URL=${_BACKEND_URL}
      - --build-arg
      - NEXT_PUBLIC_FIREBASE_VAPID_KEY=
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest
      - ./web

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --port
      - "3000"
      - --set-env-vars
      - NEXT_PUBLIC_API_URL=${_BACKEND_URL}/api,NEXT_PUBLIC_SOCKET_URL=${_BACKEND_URL}
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$BUILD_ID
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:latest
